'use client'

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'vi' | 'en'
type Theme = 'light' | 'dark'

const copy = {
  vi: {
    nav: { overview: 'Tổng quan', location: 'Vị trí', amenities: 'Tiện ích', plans: 'Mặt bằng', legal: 'Pháp lý', showUnit: 'Nhà mẫu', pricing: 'Giá bán', details: 'Chi tiết', investor: 'Chủ đầu tư', progress: 'Tiến độ', news: 'Tin tức', consult: 'Nhận tư vấn ngay', main: 'Điều hướng chính', mobile: 'Điều hướng di động', open: 'Mở menu', close: 'Đóng menu', light: 'Dùng giao diện sáng', dark: 'Dùng giao diện tối' },
    hero: { location: '236 Phan Trung, Tam Hiệp, Biên Hòa, Đồng Nai', title: 'Bcons Central Park Tam Hiệp', subtitle: 'Sống xanh giữa trung tâm Biên Hòa', description: 'Căn hộ hiện đại sở hữu lâu dài và không gian thương mại ngay lõi trung tâm sầm uất Biên Hòa. Quỹ đất gần 3 ha với công viên xanh nội khu và hệ tiện ích hiện đại.', scale: 'Quy mô', scaleValue: 'Gần 3 ha', green: 'Công viên nội khu', greenValue: 'Không gian xanh lớn', ownership: 'Sở hữu', ownershipValue: 'Lâu dài', alias: 'Dự án tại 236 Phan Trung là giải pháp an cư dài hạn và tích lũy tài sản, được phát triển bởi Tập đoàn Bcons.', register: 'Đăng ký tham quan', formTitle: 'Nhận thông tin dự án mới nhất', formDesc: 'Để lại số điện thoại, chuyên viên dự án sẽ liên hệ trong vòng 15 phút.', phone: 'Số điện thoại', placeholder: 'Số điện thoại của bạn', sent: 'Đã gửi thông tin', privacy: 'Thông tin của bạn được bảo mật và chỉ dùng để tư vấn dự án.', priceLabel: 'Giá tham khảo', price: 'Liên hệ cập nhật', viewPrice: 'Xem thông tin giá', imageAlt: 'Phối cảnh tổng thể dự án Bcons Central Park Tam Hiệp' },
    overview: { eyebrow: 'Tổng quan', title: 'Một chuẩn sống xanh giữa lõi trung tâm Biên Hòa', desc: 'Bcons Central Park Tam Hiệp kết hợp căn hộ sở hữu lâu dài, không gian thương mại và hệ tiện ích hiện đại trong một quần thể gần 3 ha.', facts: [['Tên dự án','Bcons Central Park Tam Hiệp'],['Vị trí','236 Phan Trung, P. Tam Hiệp, TP. Biên Hòa'],['Chủ đầu tư','Tập đoàn Bcons'],['Quy mô','Gần 3 ha'],['Loại hình','Căn hộ hiện đại & không gian thương mại'],['Sở hữu','Lâu dài']], stats: [['Vị trí','Trung tâm Biên Hòa'],['Quy mô','Gần 3 ha'],['Không gian','Công viên nội khu'],['Giá trị','An cư & tích lũy']], imageAlt: 'Phối cảnh toàn khu Bcons Central Park Tam Hiệp' },
    location: { eyebrow: 'Vị trí', title: 'Tọa độ kết nối của Biên Hòa', desc: 'Tọa lạc tại 236 Phan Trung, dự án nằm giữa trung tâm thương mại sôi động của Biên Hòa và kết nối thuận tiện tới các tiện ích đô thị hiện hữu.', address: '236 Phan Trung, P. Tam Hiệp, TP. Biên Hòa', imageAlt: 'Họa đồ vị trí Bcons Central Park Tam Hiệp', connections: [['1 phút','Trục Phan Trung và kết nối Quốc lộ 1A'],['3 phút','Chợ Tam Hiệp và tiện ích lân cận'],['5 phút','Bệnh viện Đa khoa Đồng Nai'],['7 phút','Trung tâm hành chính Biên Hòa'],['10 phút','Các khu công nghiệp trọng điểm'],['Kết nối','Sân bay Long Thành qua cao tốc']] },
    amenities: { eyebrow: 'Tiện ích', title: 'Hệ tiện ích hiện đại cho một nhịp sống trọn vẹn', desc: 'Từ công viên xanh nội khu, hồ bơi đến mua sắm và vận động, mọi trải nghiệm hằng ngày được bố trí ngay bên thềm nhà.', quote: 'Không gian xanh là tiện ích quý giá của một đô thị hiện đại', imageAlt: 'Hồ bơi và cảnh quan xanh nội khu dự án', items: [['Hồ bơi nội khu','Không gian thư giãn xanh mát giữa các tòa tháp.'],['Công viên xanh','Cảnh quan và đường dạo dành cho cư dân.'],['Gym & yoga','Không gian vận động hiện đại, thuận tiện.'],['Khu trẻ em','Sân chơi an toàn ngay trong khuôn viên.'],['Không gian thương mại','Mua sắm và dịch vụ ngay khối đế.'],['Cộng đồng cư dân','Không gian kết nối và sinh hoạt chung.'],['Khu đỗ xe','Hạ tầng đỗ xe thuận tiện cho toàn khu.'],['An ninh 24/7','Kiểm soát ra vào và giám sát toàn khu.']] },
    plans: { eyebrow: 'Mặt bằng', title: 'Chọn không gian phù hợp với gia đình bạn', desc: 'Các dòng căn hộ hiện đại và không gian thương mại được tổ chức linh hoạt, ưu tiên ánh sáng tự nhiên và công năng sử dụng.', tabs: 'Danh sách loại sản phẩm', plans: [['1pn','Căn 1 phòng ngủ','Diện tích tham khảo','1 PN + 1 WC','Hướng nội khu','Phù hợp người trẻ hoặc nhu cầu đầu tư cho thuê.'],['2pn','Căn 2 phòng ngủ','Diện tích tham khảo','2 PN + 2 WC','Hướng hồ bơi / thành phố','Loại căn linh hoạt cho gia đình nhỏ.'],['3pn','Căn 3 phòng ngủ','Diện tích tham khảo','3 PN + 2 WC','Căn góc, hai mặt thoáng','Không gian rộng rãi cho gia đình nhiều thế hệ.'],['shop','Không gian thương mại','Liên hệ diện tích','Mặt tiền thương mại','Tiếp giáp trục nội khu','Tận dụng cộng đồng cư dân và vị trí trung tâm.']], area: 'Diện tích', structure: 'Cấu trúc', view: 'Tầm nhìn', imageAlt: 'Mặt bằng sản phẩm' },
    showUnit: { eyebrow: 'Nhà mẫu', title: 'Trải nghiệm không gian sống trước khi quyết định', desc: 'Khám phá cách bố trí công năng, ánh sáng tự nhiên và tiêu chuẩn hoàn thiện dự kiến của căn hộ.', badge: 'Mở cửa tham quan hằng ngày', specs: ['Thiết kế hiện đại, tối ưu diện tích sử dụng','Không gian sinh hoạt đón ánh sáng tự nhiên','Vật liệu hoàn thiện được tư vấn tại nhà mẫu','Hệ thống kỹ thuật bố trí gọn gàng, tiện nghi'], cta: 'Đặt lịch tham quan nhà mẫu', imageAlt: 'Không gian sống tại Bcons Central Park Tam Hiệp' },
    pricing: { eyebrow: 'Giá bán', title: 'Thông tin giá & chính sách thanh toán', desc: 'Giá và chính sách được cập nhật theo từng thời điểm và giỏ hàng. Liên hệ để nhận thông tin chính thức cho sản phẩm phù hợp.', product: 'Loại sản phẩm', area: 'Diện tích', price: 'Thông tin giá', rows: [['Căn 1 phòng ngủ','Liên hệ','Cập nhật mới nhất'],['Căn 2 phòng ngủ','Liên hệ','Cập nhật mới nhất'],['Căn 3 phòng ngủ','Liên hệ','Cập nhật mới nhất'],['Không gian thương mại','Liên hệ','Liên hệ']], policy: 'Chính sách', policyTitle: 'Quyền lợi dành cho khách hàng quan tâm sớm', policies: ['Nhận giỏ hàng và chính sách theo từng thời điểm','Tư vấn phương án thanh toán phù hợp dòng tiền','Hỗ trợ thông tin vay theo chính sách ngân hàng','Đặt lịch tham quan dự án và nhà mẫu'], cta: 'Nhận thông tin mới nhất', caption: 'Thông tin giá theo loại sản phẩm' },
    legal: { eyebrow: 'Pháp lý', title: 'Thông tin minh bạch, tư vấn rõ ràng', items: [['Sở hữu lâu dài','Sản phẩm căn hộ được định hướng sở hữu lâu dài.'],['Thông tin dự án','Hồ sơ và tài liệu được tư vấn theo công bố chính thức.'],['Hỗ trợ tài chính','Chính sách ngân hàng được cập nhật theo từng thời điểm.'],['Cập nhật minh bạch','Tiến độ và thông tin mới được cập nhật định kỳ.']], investor: 'Chủ đầu tư', investorTitle: 'Tập đoàn Bcons — kiến tạo giá trị an cư bền vững', investorDesc: 'Bcons phát triển các sản phẩm nhà ở hướng đến nhu cầu thật, chú trọng công năng, tiện ích và giá trị sử dụng lâu dài. Bcons Central Park Tam Hiệp mở rộng dấu ấn của tập đoàn tại trung tâm Biên Hòa.', progress: 'Tiến độ', progressTitle: 'Lộ trình triển khai dự án', progressDesc: 'Các mốc triển khai sẽ được cập nhật theo thông báo chính thức từ chủ đầu tư.', timeline: [['Chuẩn bị','Cập nhật','Hoàn thiện hồ sơ và công tác chuẩn bị dự án.'],['Thi công','Cập nhật','Triển khai các hạng mục theo kế hoạch.'],['Hoàn thiện','Cập nhật','Hoàn thiện công trình và cảnh quan.'],['Bàn giao','Cập nhật','Thông tin dự kiến theo công bố chính thức.']] },
    news: { eyebrow: 'Tin tức', title: 'Thông tin mới nhất về dự án và khu vực', read: 'Đọc tiếp', posts: [['Thị trường','Kết nối hạ tầng nâng tầm giá trị trung tâm Biên Hòa'],['Dự án','Khám phá không gian xanh tại Bcons Central Park Tam Hiệp'],['Kinh nghiệm','Những lưu ý khi lựa chọn căn hộ sở hữu lâu dài']] },
    contact: { eyebrow: 'Đăng ký tư vấn', title: 'Nhận thông tin dự án và chính sách mới nhất', desc: 'Chuyên viên sẽ gửi thông tin sản phẩm, phương án thanh toán phù hợp và hỗ trợ sắp xếp lịch tham quan.', hotline: 'Hotline', email: 'Email', showroom: 'Nhà mẫu', name: 'Họ và tên', namePlaceholder: 'Nguyễn Văn A', phone: 'Số điện thoại', type: 'Sản phẩm quan tâm', note: 'Ghi chú', notePlaceholder: 'Tôi muốn nhận thông tin và đặt lịch tham quan...', options: ['1 phòng ngủ','2 phòng ngủ','3 phòng ngủ','Không gian thương mại'], submit: 'Gửi thông tin', sent: 'Cảm ơn bạn, chúng tôi sẽ liên hệ sớm' },
    footer: { project: 'Dự án', info: 'Thông tin', support: 'Hỗ trợ', description: 'Trang thông tin Bcons Central Park Tam Hiệp — căn hộ sở hữu lâu dài và không gian thương mại tại 236 Phan Trung, Tam Hiệp, Biên Hòa, Đồng Nai.', disclaimer: 'Thông tin mang tính tham khảo.', changes: 'Hình ảnh và thông tin có thể thay đổi theo công bố của chủ đầu tư.', register: 'Đăng ký tư vấn', actions: ['Nhắn tin Facebook','Chat Zalo','Gọi hotline 0938 000 111'] }
  },
  en: {
    nav: { overview: 'Overview', location: 'Location', amenities: 'Amenities', plans: 'Floor plans', legal: 'Legal', showUnit: 'Show unit', pricing: 'Pricing', details: 'Details', investor: 'Developer', progress: 'Progress', news: 'News', consult: 'Get consultation', main: 'Main navigation', mobile: 'Mobile navigation', open: 'Open menu', close: 'Close menu', light: 'Use light mode', dark: 'Use dark mode' },
    hero: { location: '236 Phan Trung, Tam Hiep, Bien Hoa, Dong Nai', title: 'Bcons Central Park Tam Hiep', subtitle: 'Green living in central Bien Hoa', description: 'Modern long-term ownership apartments and commercial spaces in Bien Hoa’s vibrant urban core. Nearly 3 hectares with a large internal green park and contemporary amenities.', scale: 'Scale', scaleValue: 'Nearly 3 ha', green: 'Internal park', greenValue: 'Expansive greenery', ownership: 'Ownership', ownershipValue: 'Long-term', alias: 'Located at 236 Phan Trung, the project is designed for long-term living and asset accumulation by Bcons Group.', register: 'Book a visit', formTitle: 'Receive the latest project information', formDesc: 'Leave your phone number and a consultant will contact you within 15 minutes.', phone: 'Phone number', placeholder: 'Your phone number', sent: 'Information sent', privacy: 'Your information is kept private and used only for project consultation.', priceLabel: 'Reference pricing', price: 'Contact for updates', viewPrice: 'View pricing details', imageAlt: 'Bcons Central Park Tam Hiep project rendering' },
    overview: { eyebrow: 'Overview', title: 'A green living standard in central Bien Hoa', desc: 'Bcons Central Park Tam Hiep combines long-term ownership apartments, commercial spaces and modern amenities across nearly 3 hectares.', facts: [['Project','Bcons Central Park Tam Hiep'],['Location','236 Phan Trung, Tam Hiep, Bien Hoa'],['Developer','Bcons Group'],['Scale','Nearly 3 hectares'],['Product','Modern apartments & commercial spaces'],['Ownership','Long-term']], stats: [['Location','Central Bien Hoa'],['Scale','Nearly 3 ha'],['Landscape','Internal green park'],['Value','Living & accumulation']], imageAlt: 'Bcons Central Park Tam Hiep master rendering' },
    location: { eyebrow: 'Location', title: 'Connected at the heart of Bien Hoa', desc: 'At 236 Phan Trung, the project sits within Bien Hoa’s vibrant commercial center and connects easily to established urban amenities.', address: '236 Phan Trung, Tam Hiep, Bien Hoa', imageAlt: 'Bcons Central Park Tam Hiep location map', connections: [['1 min','Phan Trung axis and National Highway 1A'],['3 mins','Tam Hiep Market and nearby services'],['5 mins','Dong Nai General Hospital'],['7 mins','Bien Hoa administrative center'],['10 mins','Major industrial parks'],['Connected','Long Thanh Airport via expressway']] },
    amenities: { eyebrow: 'Amenities', title: 'Modern amenities for a complete lifestyle', desc: 'From the internal green park and pool to shopping and fitness, everyday experiences are just steps from home.', quote: 'Green space is the most valuable amenity in a modern city', imageAlt: 'Pool and green internal landscape', items: [['Internal pool','A lush retreat between the residential towers.'],['Green park','Landscaped gardens and resident walkways.'],['Gym & yoga','Convenient modern fitness spaces.'],['Kids’ zone','A safe play area within the community.'],['Commercial spaces','Daily shopping and services at the podium.'],['Community spaces','Places to connect, meet and gather.'],['Parking','Convenient parking infrastructure for residents.'],['24/7 security','Controlled access and community monitoring.']] },
    plans: { eyebrow: 'Floor plans', title: 'Choose the space that fits your family', desc: 'Modern apartments and commercial spaces are organized flexibly with a focus on daylight and practical living.', tabs: 'Product type list', plans: [['1pn','One-bedroom apartment','Area on request','1 bed + 1 bath','Internal park view','Ideal for young residents or rental investment.'],['2pn','Two-bedroom apartment','Area on request','2 beds + 2 baths','Pool / city view','A flexible choice for a small family.'],['3pn','Three-bedroom apartment','Area on request','3 beds + 2 baths','Corner, dual aspect','Generous living for larger families.'],['shop','Commercial space','Contact for area','Retail frontage','Internal street frontage','Benefit from the resident community and central location.']], area: 'Area', structure: 'Layout', view: 'View', imageAlt: 'Product floor plan' },
    showUnit: { eyebrow: 'Show unit', title: 'Experience the living space before deciding', desc: 'Explore the functionality, natural light and proposed finishing standards of the apartments.', badge: 'Open daily for visits', specs: ['Modern design with optimized usable area','Living spaces filled with natural daylight','Finishing materials presented at the show unit','Thoughtfully integrated technical systems'], cta: 'Book a show unit visit', imageAlt: 'Living experience at Bcons Central Park Tam Hiep' },
    pricing: { eyebrow: 'Pricing', title: 'Pricing & payment information', desc: 'Pricing and policies vary by release and available inventory. Contact us for official information on the right product.', product: 'Product type', area: 'Area', price: 'Pricing', rows: [['One-bedroom apartment','Contact','Latest update'],['Two-bedroom apartment','Contact','Latest update'],['Three-bedroom apartment','Contact','Latest update'],['Commercial space','Contact','Contact']], policy: 'Policy', policyTitle: 'Benefits for early interested buyers', policies: ['Receive current inventory and policies','Payment-plan consultation based on cash flow','Bank financing information when available','Project and show unit visit assistance'], cta: 'Get the latest information', caption: 'Pricing by product type' },
    legal: { eyebrow: 'Legal', title: 'Transparent information, clear consultation', items: [['Long-term ownership','Apartments are positioned for long-term ownership.'],['Project information','Documents are shared according to official announcements.'],['Finance support','Bank policies are updated for each period.'],['Transparent updates','Progress and project news are updated regularly.']], investor: 'Developer', investorTitle: 'Bcons Group — creating lasting residential value', investorDesc: 'Bcons develops homes for real demand with a focus on functionality, amenities and lasting value. Bcons Central Park Tam Hiep expands the group’s presence into central Bien Hoa.', progress: 'Progress', progressTitle: 'Project delivery roadmap', progressDesc: 'Milestones will be updated according to official announcements from the developer.', timeline: [['Preparation','Update','Project documentation and preparation.'],['Construction','Update','Construction work according to plan.'],['Completion','Update','Building and landscape completion.'],['Handover','Update','Expected details subject to official announcement.']] },
    news: { eyebrow: 'News', title: 'Latest project and area updates', read: 'Read more', posts: [['Market','Infrastructure links strengthen central Bien Hoa'],['Project','Explore green living at Bcons Central Park Tam Hiep'],['Guide','What to consider when choosing a long-term ownership home']] },
    contact: { eyebrow: 'Consultation', title: 'Receive the latest project and policy information', desc: 'A consultant will share product details, suitable payment options and help arrange a visit.', hotline: 'Hotline', email: 'Email', showroom: 'Show unit', name: 'Full name', namePlaceholder: 'Your name', phone: 'Phone number', type: 'Interested product', note: 'Note', notePlaceholder: 'I would like project information and a visit...', options: ['One bedroom','Two bedrooms','Three bedrooms','Commercial space'], submit: 'Send information', sent: 'Thank you, we will contact you soon' },
    footer: { project: 'Project', info: 'Information', support: 'Support', description: 'Bcons Central Park Tam Hiep information page — long-term ownership apartments and commercial spaces at 236 Phan Trung, Tam Hiep, Bien Hoa, Dong Nai.', disclaimer: 'Information is for reference.', changes: 'Images and information may change under developer announcements.', register: 'Request consultation', actions: ['Message on Facebook','Chat on Zalo','Call hotline 0938 000 111'] }
  }
} as const

type SiteContextValue = { locale: Locale; setLocale: (locale: Locale) => void; theme: Theme; toggleTheme: () => void; t: (typeof copy)[Locale] }
const SiteContext = createContext<SiteContextValue | null>(null)

export function SitePreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('vi')
  const [theme, setTheme] = useState<Theme>('light')

  useEffect(() => {
    const savedLocale = localStorage.getItem('bcons-locale') as Locale | null
    const savedTheme = localStorage.getItem('bcons-theme') as Theme | null
    if (savedLocale === 'vi' || savedLocale === 'en') setLocaleState(savedLocale)
    const initialTheme = savedTheme === 'dark' ? 'dark' : 'light'
    setTheme(initialTheme)
    document.documentElement.classList.toggle('dark', initialTheme === 'dark')
  }, [])

  const setLocale = (next: Locale) => {
    setLocaleState(next)
    localStorage.setItem('bcons-locale', next)
    document.documentElement.lang = next
  }
  const toggleTheme = () => setTheme((current) => {
    const next = current === 'light' ? 'dark' : 'light'
    localStorage.setItem('bcons-theme', next)
    document.documentElement.classList.toggle('dark', next === 'dark')
    return next
  })
  const value = useMemo(() => ({ locale, setLocale, theme, toggleTheme, t: copy[locale] }), [locale, theme])
  return <SiteContext.Provider value={value}>{children}</SiteContext.Provider>
}

export function useSitePreferences() {
  const context = useContext(SiteContext)
  if (!context) throw new Error('useSitePreferences must be used inside SitePreferencesProvider')
  return context
}
