export interface NhaMauItem {
  id: string
  type: 'a1' | 'b4' | 'c1'
  typeName: string
  typeNameEn: string
  caption: string
  captionEn: string
  src: string
}

export interface ApartmentConfig {
  id: 'a1' | 'b4' | 'c1'
  code: string
  bedrooms: string
  bedroomsEn: string
  floorArea: string
  usableArea: string
  count: number
  desc: string
  descEn: string
  badge: string
  badgeEn: string
  features: string[]
  featuresEn: string[]
}

export const apartmentConfigs: Record<'a1' | 'b4' | 'c1', ApartmentConfig> = {
  a1: {
    id: 'a1',
    code: 'Căn A1',
    bedrooms: '3 phòng ngủ',
    bedroomsEn: '3 Bedrooms',
    floorArea: '88 m²',
    usableArea: '81 m²',
    count: 14,
    desc: '3 phòng ngủ · sàn 88 m² · sử dụng 81 m²',
    descEn: '3 Bedrooms · Gross 88 m² · Net 81 m²',
    badge: 'Căn 3PN lớn nhất dự án',
    badgeEn: 'Largest 3-Bedroom Unit',
    features: [
      'Phòng khách rộng rãi, kết nối trực tiếp ban công thoáng đãng',
      'Phòng ngủ chính (Master) có phòng vệ sinh riêng và góc bàn trang điểm',
      '2 phòng ngủ phụ tối ưu cho con cái và góc làm việc / học tập riêng',
      'Bếp chữ L thông thoáng liền kề lô gia giặt phơi biệt lập',
    ],
    featuresEn: [
      'Spacious living room directly connected to an airy balcony',
      'Master bedroom suite with private en-suite bathroom and vanity corner',
      '2 secondary bedrooms optimized for children and dedicated study/work nook',
      'Ventilated L-shaped kitchen adjacent to a separated laundry loggia',
    ],
  },
  b4: {
    id: 'b4',
    code: 'Căn B4',
    bedrooms: '2 phòng ngủ',
    bedroomsEn: '2 Bedrooms',
    floorArea: '73 m²',
    usableArea: '67 – 69 m²',
    count: 14,
    desc: '2 phòng ngủ · sàn 73 m² · sử dụng 67 – 69 m²',
    descEn: '2 Bedrooms · Gross 73 m² · Net 67 – 69 m²',
    badge: 'Căn góc 2 mặt thoáng',
    badgeEn: 'Corner Unit with 2 Open Facades',
    features: [
      'Vị trí căn góc đón trọn 2 luồng gió tươi và ánh sáng tự nhiên',
      'Sảnh vào tích hợp hệ tủ giày kịch trần và tủ rượu decor sang trọng',
      'Phòng khách & bàn ăn vuông vức, tối ưu hóa không gian sum vầy',
      '2 phòng vệ sinh trang bị thiết bị cao cấp, lô gia giặt đón nắng gió',
    ],
    featuresEn: [
      'Corner position capturing dual natural airflow and daylight',
      'Foyer integrated with full-height shoe storage and luxury wine display',
      'Square living and dining layout maximizing family gathering space',
      '2 modern bathrooms with premium fixtures, sunny laundry loggia',
    ],
  },
  c1: {
    id: 'c1',
    code: 'Căn C1',
    bedrooms: '2 phòng ngủ',
    bedroomsEn: '2 Bedrooms',
    floorArea: '52 m²',
    usableArea: '47 – 48 m²',
    count: 17,
    desc: '2 phòng ngủ · sàn 52 m² · sử dụng 47 – 48 m²',
    descEn: '2 Bedrooms · Gross 52 m² · Net 47 – 48 m²',
    badge: 'Thiết kế thông minh kiểu Nhật',
    badgeEn: 'Smart Japanese-Inspired Layout',
    features: [
      'Thiết kế phong cách Nhật Bản tinh tế, tối ưu hóa từng cm² sử dụng',
      'Hệ vách lùa Shoji linh hoạt biến tấu giữa không gian mở và riêng tư',
      'Phòng ngủ trẻ em bài trí giường bục đa năng tích hợp ngăn kéo chứa đồ',
      'Chi phí sở hữu vừa vặn, thanh khoản cao, phù hợp gia đình trẻ & đầu tư',
    ],
    featuresEn: [
      'Refined Japanese minimalist design optimizing every square meter',
      'Flexible Shoji sliding partitions converting between open & private areas',
      'Kids room equipped with multifunctional podium bed and smart storage drawers',
      'Accessible initial capital, high liquidity, ideal for young couples & investors',
    ],
  },
}

export const nhaMauImages: NhaMauItem[] = [
  // CĂN A1 (14 photos)
  {
    id: 'a1-1',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng khách – vách TV',
    captionEn: 'Living Room – TV Wall',
    src: '/images/nha-mau/a1-01-bcons-central-park-nha-mau-a1-phong-khach.wQVLyslN_ZSqv2q.webp',
  },
  {
    id: 'a1-2',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng khách nhìn từ bàn ăn',
    captionEn: 'Living Room View from Dining Table',
    src: '/images/nha-mau/a1-02-bcons-central-park-nha-mau-a1-phong-khach-ban-an.D0yg04J-_1OUPXP.webp',
  },
  {
    id: 'a1-3',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Bàn ăn & sinh hoạt chung',
    captionEn: 'Dining Table & Common Living Area',
    src: '/images/nha-mau/a1-03-bcons-central-park-nha-mau-a1-ban-an.CVkKuknL_gQlBF.webp',
  },
  {
    id: 'a1-4',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Lối vào & tủ giày',
    captionEn: 'Entrance Foyer & Shoe Cabinet',
    src: '/images/nha-mau/a1-04-bcons-central-park-nha-mau-a1-loi-vao-tu-giay.Bi8cq_Bx_1oVWIR.webp',
  },
  {
    id: 'a1-5',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Bếp & khu giặt',
    captionEn: 'Kitchen & Laundry Area',
    src: '/images/nha-mau/a1-05-bcons-central-park-nha-mau-a1-bep.BQH20pMX_JVsKQ.webp',
  },
  {
    id: 'a1-6',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ chính',
    captionEn: 'Master Bedroom',
    src: '/images/nha-mau/a1-06-bcons-central-park-nha-mau-a1-phong-ngu-chinh-01.xvNy-wID_4tTAD.webp',
  },
  {
    id: 'a1-7',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ chính – góc trang điểm',
    captionEn: 'Master Bedroom – Vanity & Dressing Corner',
    src: '/images/nha-mau/a1-07-bcons-central-park-nha-mau-a1-phong-ngu-chinh-02.C4-9z7tX_IIr8b.webp',
  },
  {
    id: 'a1-8',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ chính – tủ áo & vách TV',
    captionEn: 'Master Bedroom – Wardrobe & TV Wall',
    src: '/images/nha-mau/a1-08-bcons-central-park-nha-mau-a1-phong-ngu-chinh-03.I_NhK2eU_Z1j1wgB.webp',
  },
  {
    id: 'a1-9',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ 2',
    captionEn: 'Bedroom 2',
    src: '/images/nha-mau/a1-09-bcons-central-park-nha-mau-a1-phong-ngu-2-01.YbJLEujh_Z1z6hEz.webp',
  },
  {
    id: 'a1-10',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ 2 – góc làm việc',
    captionEn: 'Bedroom 2 – Work Desk Corner',
    src: '/images/nha-mau/a1-10-bcons-central-park-nha-mau-a1-phong-ngu-2-ban-lam-viec.Nx_gOwlM_29Jm0z.webp',
  },
  {
    id: 'a1-11',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ 2 – tủ áo',
    captionEn: 'Bedroom 2 – Wardrobe',
    src: '/images/nha-mau/a1-11-bcons-central-park-nha-mau-a1-phong-ngu-2-tu-ao.ght1dX9J_Z2hSpQ3.webp',
  },
  {
    id: 'a1-12',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ bé',
    captionEn: "Kids Bedroom",
    src: '/images/nha-mau/a1-12-bcons-central-park-nha-mau-a1-phong-ngu-be-01.DPXJCyQ4_ZhB32q.webp',
  },
  {
    id: 'a1-13',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ bé – tủ áo & bàn học',
    captionEn: "Kids Bedroom – Wardrobe & Study Desk",
    src: '/images/nha-mau/a1-13-bcons-central-park-nha-mau-a1-phong-ngu-be-tu-ao.BWEoc8HH_1xyAEN.webp',
  },
  {
    id: 'a1-14',
    type: 'a1',
    typeName: 'Căn A1 · 88 m²',
    typeNameEn: 'Unit A1 · 88 m²',
    caption: 'Phòng ngủ bé – góc chơi',
    captionEn: "Kids Bedroom – Play Corner",
    src: '/images/nha-mau/a1-14-bcons-central-park-nha-mau-a1-phong-ngu-be-goc-choi.BxpjHtlb_ZFaTbB.webp',
  },

  // CĂN B4 (14 photos)
  {
    id: 'b4-15',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng khách',
    captionEn: 'Living Room',
    src: '/images/nha-mau/b4-15-bcons-central-park-nha-mau-b4-phong-khach.KiaCBx3v_Z207Okl.webp',
  },
  {
    id: 'b4-16',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng khách & bàn ăn',
    captionEn: 'Living & Dining Room',
    src: '/images/nha-mau/b4-16-bcons-central-park-nha-mau-b4-phong-khach-ban-an.DFDJFZqp_ZbnQ0M.webp',
  },
  {
    id: 'b4-17',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Bếp & bàn ăn',
    captionEn: 'Kitchen & Dining Setup',
    src: '/images/nha-mau/b4-17-bcons-central-park-nha-mau-b4-bep-ban-an.C9tMIcqS_bw0L3.webp',
  },
  {
    id: 'b4-18',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Lối vào – tủ giày & tủ rượu',
    captionEn: 'Entrance – Shoe Cabinet & Wine Display',
    src: '/images/nha-mau/b4-18-bcons-central-park-nha-mau-b4-loi-vao-tu-ruou.DiE2CdsM_1gQi4.webp',
  },
  {
    id: 'b4-19',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ chính',
    captionEn: 'Master Bedroom',
    src: '/images/nha-mau/b4-19-bcons-central-park-nha-mau-b4-phong-ngu-chinh-01.DKiZnRC0_1L9b8c.webp',
  },
  {
    id: 'b4-20',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ chính – tủ áo',
    captionEn: 'Master Bedroom – Wardrobe',
    src: '/images/nha-mau/b4-20-bcons-central-park-nha-mau-b4-phong-ngu-chinh-tu-ao.DxXPS8to_Z1CDVyh.webp',
  },
  {
    id: 'b4-21',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ chính – góc cửa sổ',
    captionEn: 'Master Bedroom – Window View Corner',
    src: '/images/nha-mau/b4-21-bcons-central-park-nha-mau-b4-phong-ngu-chinh-cua-so.Dk-njOYd_7UkRw.webp',
  },
  {
    id: 'b4-22',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ chính – vách TV',
    captionEn: 'Master Bedroom – TV Wall Accent',
    src: '/images/nha-mau/b4-22-bcons-central-park-nha-mau-b4-phong-ngu-chinh-vach-tv.DI9hhAbv_Zl1qAu.webp',
  },
  {
    id: 'b4-23',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ bé',
    captionEn: "Kids Bedroom",
    src: '/images/nha-mau/b4-23-bcons-central-park-nha-mau-b4-phong-ngu-be-01.D9WmPRbM_jS12l.webp',
  },
  {
    id: 'b4-24',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ bé – bàn học & tủ áo',
    captionEn: "Kids Bedroom – Study Desk & Wardrobe",
    src: '/images/nha-mau/b4-24-bcons-central-park-nha-mau-b4-phong-ngu-be-ban-hoc.6-bnuta6_Z20uNry.webp',
  },
  {
    id: 'b4-25',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng ngủ bé – tranh tường',
    captionEn: "Kids Bedroom – Creative Mural Wall",
    src: '/images/nha-mau/b4-25-bcons-central-park-nha-mau-b4-phong-ngu-be-tranh-tuong.gwolBwUC_1DJyg5.webp',
  },
  {
    id: 'b4-26',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng tắm',
    captionEn: 'Bathroom',
    src: '/images/nha-mau/b4-26-bcons-central-park-nha-mau-b4-phong-tam-01.BbRMfn2Y_8Codp.webp',
  },
  {
    id: 'b4-27',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Phòng tắm – bồn rửa & gương',
    captionEn: 'Bathroom – Basin & LED Vanity Mirror',
    src: '/images/nha-mau/b4-27-bcons-central-park-nha-mau-b4-phong-tam-02.CjKNKifZ_Z1wV81g.webp',
  },
  {
    id: 'b4-28',
    type: 'b4',
    typeName: 'Căn B4 · 73 m²',
    typeNameEn: 'Unit B4 · 73 m²',
    caption: 'Khu giặt tại lô gia',
    captionEn: 'Laundry Area at Loggia',
    src: '/images/nha-mau/b4-28-bcons-central-park-nha-mau-b4-khu-giat-lo-gia.CXp5Mif4_2saIoX.webp',
  },

  // CĂN C1 (17 photos)
  {
    id: 'c1-29',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Tổng thể bếp – bàn ăn – phòng khách',
    captionEn: 'Open Layout: Kitchen – Dining – Living',
    src: '/images/nha-mau/c1-29-bcons-central-park-nha-mau-c1-tong-the-bep-ban-an-phong-khach.BmSQVhvr_ZQz4ki.webp',
  },
  {
    id: 'c1-30',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng khách nhìn ra ban công',
    captionEn: 'Living Room Facing Private Balcony',
    src: '/images/nha-mau/c1-30-bcons-central-park-nha-mau-c1-phong-khach-ban-cong.nmx6hH0t_2goYyC.webp',
  },
  {
    id: 'c1-31',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng khách & bàn ăn',
    captionEn: 'Living & Dining Harmony',
    src: '/images/nha-mau/c1-31-bcons-central-park-nha-mau-c1-phong-khach-ban-an.MkNpoWxG_1oCFWO.webp',
  },
  {
    id: 'c1-32',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Bàn ăn',
    captionEn: 'Dining Table Setting',
    src: '/images/nha-mau/c1-32-bcons-central-park-nha-mau-c1-ban-an.B7nyQUAj_Oq14u.webp',
  },
  {
    id: 'c1-33',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng khách nhìn về lối vào',
    captionEn: 'Living Room View Towards Entrance',
    src: '/images/nha-mau/c1-33-bcons-central-park-nha-mau-c1-phong-khach-loi-vao.IVgxhjc8_Z1ka9Jv.webp',
  },
  {
    id: 'c1-34',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Bếp & khu giặt',
    captionEn: 'Kitchen & Integrated Laundry',
    src: '/images/nha-mau/c1-34-bcons-central-park-nha-mau-c1-bep.DQkLSJr2_Z1I5Pfd.webp',
  },
  {
    id: 'c1-35',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Lối vào & vách gỗ trang trí',
    captionEn: 'Entrance Foyer & Wooden Accent Screen',
    src: '/images/nha-mau/c1-35-bcons-central-park-nha-mau-c1-loi-vao-vach-go.B-Bk8xQO_Z1cul8g.webp',
  },
  {
    id: 'c1-36',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ chính – vách shoji',
    captionEn: 'Master Bedroom – Japanese Shoji Sliding Wall',
    src: '/images/nha-mau/c1-36-bcons-central-park-nha-mau-c1-phong-ngu-chinh-vach-shoji.B21niOb4_LVlFr.webp',
  },
  {
    id: 'c1-37',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ chính – bàn trang điểm',
    captionEn: 'Master Bedroom – Vanity Desk',
    src: '/images/nha-mau/c1-37-bcons-central-park-nha-mau-c1-phong-ngu-chinh-ban-trang-diem.DNM-4Gxo_kCL1u.webp',
  },
  {
    id: 'c1-38',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ chính',
    captionEn: 'Master Bedroom Comfort',
    src: '/images/nha-mau/c1-38-bcons-central-park-nha-mau-c1-phong-ngu-chinh-01.Osh24Jmf_Zak5Xm.webp',
  },
  {
    id: 'c1-39',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ chính – tủ áo & gương',
    captionEn: 'Master Bedroom – Wardrobe & Mirror',
    src: '/images/nha-mau/c1-39-bcons-central-park-nha-mau-c1-phong-ngu-chinh-02.BjxxhpX6_Z1jYibD.webp',
  },
  {
    id: 'c1-40',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ – vách TV',
    captionEn: 'Bedroom – Wall TV Setup',
    src: '/images/nha-mau/c1-40-bcons-central-park-nha-mau-c1-phong-ngu-vach-tv.Ch9iI0vo_Z1D68MT.webp',
  },
  {
    id: 'c1-41',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ nhìn ra bàn ăn',
    captionEn: 'Bedroom View Towards Dining Area',
    src: '/images/nha-mau/c1-41-bcons-central-park-nha-mau-c1-phong-ngu-nhin-ra-ban-an.CLYKSTER_Z11tFfI.webp',
  },
  {
    id: 'c1-42',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ bé',
    captionEn: "Kids Bedroom",
    src: '/images/nha-mau/c1-42-bcons-central-park-nha-mau-c1-phong-ngu-be-01.C-NDTQNN_ZRftIg.webp',
  },
  {
    id: 'c1-43',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ bé – giường bục',
    captionEn: "Kids Bedroom – Multifunctional Platform Bed",
    src: '/images/nha-mau/c1-43-bcons-central-park-nha-mau-c1-phong-ngu-be-giuong-buc.9klMhEA6_Z1aYrgu.webp',
  },
  {
    id: 'c1-44',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng ngủ bé – tường xanh',
    captionEn: "Kids Bedroom – Sage Green Accent Wall",
    src: '/images/nha-mau/c1-44-bcons-central-park-nha-mau-c1-phong-ngu-be-tuong-xanh.BhxhAk02_26RDvh.webp',
  },
  {
    id: 'c1-45',
    type: 'c1',
    typeName: 'Căn C1 · 52 m²',
    typeNameEn: 'Unit C1 · 52 m²',
    caption: 'Phòng tắm & khu giặt',
    captionEn: 'Bathroom & Laundry Unit',
    src: '/images/nha-mau/c1-45-bcons-central-park-nha-mau-c1-phong-tam-khu-giat.tV3cCz2__1DzjbO.webp',
  },
]

export const handoverHighlights = [
  {
    title: 'Vật liệu hoàn thiện thực tế',
    titleEn: 'Actual Handover Materials',
    desc: 'Vật liệu và thiết bị dựng đúng theo danh mục cam kết bàn giao trong Hợp đồng mua bán từ Tập đoàn Bcons.',
    descEn: 'Materials and fixtures accurately match the binding handover annex in the sales contract from Bcons Group.',
  },
  {
    title: 'Bố trí công năng tối ưu',
    titleEn: 'Optimized Functional Layout',
    desc: '100% căn hộ sở hữu ban công phòng khách và lô gia riêng biệt, tận dụng tối đa ánh sáng và gió đối lưu tự nhiên.',
    descEn: '100% of units feature a living room balcony and separated laundry loggia, maximizing natural daylight and airflow.',
  },
  {
    title: 'Trải nghiệm trực tiếp không gian',
    titleEn: 'Direct Real Space Experience',
    desc: 'Chạm tay vào vật liệu thật, cảm nhận chiều cao trần thông thuỷ và kiểm tra công năng trước khi đặt cọc.',
    descEn: 'Touch real materials, sense the actual ceiling height, and inspect usability before placing your deposit.',
  },
]

export const inspectionChecklist = [
  {
    num: 1,
    title: 'Diện tích tim tường hay thông thuỷ',
    titleEn: 'Gross vs. Net Usable Area',
    desc: 'Hỏi rõ căn mẫu tương ứng loại căn nào và ghi lại cả hai con số. Diện tích thông thuỷ (LL) thấp hơn tim tường (TT) khoảng 8 – 11% tuỳ căn. Con số ghi trên hợp đồng mua bán là diện tích thông thuỷ.',
    descEn: 'Clarify unit code and verify both figures. Net usable area (LL) is approx. 8 – 11% less than gross wall-center area (TT). The sales contract legally uses the net usable area.',
  },
  {
    num: 2,
    title: 'Danh mục vật liệu bàn giao bằng văn bản',
    titleEn: 'Written Handover Fixtures List',
    desc: 'Yêu cầu bản phụ lục vật liệu và thiết bị bàn giao, rồi đối chiếu từng dòng với thứ đang nhìn thấy: sàn gỗ, gạch lát, trần thạch cao, thiết bị vệ sinh, tủ bếp, ổ cắm và khoá thông minh.',
    descEn: 'Request the official handover annex and cross-check each line: flooring, ceiling, bathroom sanitary ware, kitchen cabinets, sockets, and digital smart lock.',
  },
  {
    num: 3,
    title: 'Phân biệt nội thất bàn giao và đồ trang trí',
    titleEn: 'Distinguish Fit-Out from Decor',
    desc: 'Nhà mẫu thường được bài trí bằng nội thất rời thiết kế riêng cho vừa khít không gian, phối gương để tạo cảm giác rộng hơn. Đây là chi phí phát sinh sau bàn giao, cần tách khỏi ngân sách mua căn hộ.',
    descEn: 'Show units showcase custom loose furniture and mirrors to enhance spatial perception. These decorative items are post-handover investments to plan separately.',
  },
  {
    num: 4,
    title: 'Hộp kỹ thuật, cục nóng và lô gia',
    titleEn: 'Utility Shafts, AC Units & Loggia',
    desc: 'Những hạng mục này ăn vào diện tích sử dụng thật và quyết định việc bố trí đồ đạc. Xem vị trí của chúng trong nhà mẫu, sau đó đối chiếu lại trên mặt bằng tầng của đúng căn bạn định mua.',
    descEn: 'Shafts and outdoor AC compressors affect usable space and furniture placement. Inspect their position in the show unit and verify on your chosen floor plan.',
  },
  {
    num: 5,
    title: 'Hướng nhìn và vị trí căn trên tầng',
    titleEn: 'Sun Orientation & Floor Position',
    desc: 'Nhà mẫu dùng ánh sáng dàn dựng nghệ thuật nên không phản ánh hướng nắng thật. Hãy xem mặt bằng tầng điển hình Bcons Central Park để xác định căn bạn quan tâm quay về hướng nào và đón gió ra sao.',
    descEn: 'Show units use studio staging lighting. Consult the floor plan and cardinal orientation to verify your specific unit’s sun exposure and panoramic vistas.',
  },
  {
    num: 6,
    title: 'Chiều cao thông thuỷ và tiến độ bàn giao',
    titleEn: 'Ceiling Height & Handover Schedule',
    desc: 'Hỏi chiều cao thông thuỷ sau khi hoàn thiện trần thạch cao (thường 2.7m – 2.8m). Đồng thời đối chiếu mốc bàn giao Quý II/2029 với kế hoạch tài chính và dòng tiền chi trả của bạn.',
    descEn: 'Ask for the net ceiling height after gypsum ceiling installation. Cross-reference the Q2/2029 handover milestone with your personal financial cash flow plan.',
  },
]

export const showhouseFaqs = [
  {
    question: 'Nhà mẫu Bcons Central Park đặt ở đâu và mở cửa khi nào?',
    questionEn: 'Where is the Bcons Central Park show unit located and when is it open?',
    answer:
      'Nhà mẫu toạ lạc tại trung tâm TP. Biên Hòa (Đồng Nai), mở cửa đón khách tham quan từ 08:00 đến 18:00 tất cả các ngày trong tuần (kể cả Thứ 7 & Chủ Nhật). Quý khách nên đăng ký trước để được Giám đốc Sàn Lê Ngọc Long hoặc chuyên viên chuẩn bị sẵn tài liệu và đón tiếp chu đáo.',
    answerEn:
      'The model house is located in the heart of Bien Hoa City, open daily from 08:00 to 18:00 (including weekends). We recommend booking in advance so Sales Director Le Ngoc Long and our specialist team can prepare comprehensive documents and welcome you.',
  },
  {
    question: 'Nhà mẫu có giống hệt căn hộ được bàn giao không?',
    questionEn: 'Is the show unit identical to the handed-over apartment?',
    answer:
      'Kích thước không gian và vật liệu hoàn thiện cố định (sàn gạch ceramic/gỗ, tường sơn nước, trần thạch cao, thiết bị vệ sinh, hệ thống cửa khoá từ thông minh) được thi công chuẩn xác 100% theo danh mục bàn giao. Các thiết bị nội thất rời như sofa, rèm cửa, tranh ảnh, đồ điện tử được bài trí làm gợi ý thiết kế không gian sống.',
    answerEn:
      'Spatial dimensions and fixed finishing materials (wood/ceramic flooring, painted walls, gypsum ceilings, sanitary ware, smart digital locks) are constructed 100% matching the legal contract annex. Loose items like sofas, curtains, and TVs are display suggestions.',
  },
  {
    question: 'Diện tích ghi trên hợp đồng là tim tường hay thông thuỷ?',
    questionEn: 'Is the contract area based on gross wall-center or net usable area?',
    answer:
      'Hợp đồng mua bán căn hộ Bcons Central Park ghi nhận diện tích thông thuỷ (diện tích lọt lòng sử dụng thực tế). Trên mặt bằng tầng điển hình, chủ đầu tư công bố song song cả hai thông số: tim tường (TT) và thông thuỷ (LL) với mức chênh lệch khoảng 8 – 11% tuỳ theo vị trí căn góc hoặc căn giữa.',
    answerEn:
      'The Bcons Central Park purchase agreement records the net usable area (carpet area). On typical floor plan sheets, the developer displays both TT (gross) and LL (net usable) figures, with an 8 – 11% difference depending on corner or standard layouts.',
  },
  {
    question: 'Đi xem nhà mẫu có phải đặt cọc hay mất phí gì không?',
    questionEn: 'Is there any fee or deposit required to visit the model house?',
    answer:
      'Hoàn toàn KHÔNG. Buổi tham quan nhà mẫu là hoàn toàn miễn phí và không có bất kỳ ràng buộc tài chính hay đặt cọc nào. Quý khách được tham quan thực tế 3 mẫu căn A1, B4, C1, thưởng thức trà bánh và nhận bộ phân tích bảng giá chuyên sâu.',
    answerEn:
      'Absolutely NO. Visiting the showhouse is completely free without any financial obligation or deposit. Guests explore the 3 actual model units (A1, B4, C1), enjoy tea refreshments, and receive comprehensive pricing analysis kits.',
  },
]
